import { Match, MatchFormat, MatchStatus, ExtraType, WicketType } from "../interfaces/Match";

export const mockMatch: Match = {
  id: "match-001",
  format: MatchFormat.T20,
  venue: "Melbourne Cricket Ground",
  date: "2025-05-30",
  status: MatchStatus.LIVE,
  teams: {
    team1: {
      id: "team-001",
      name: "India",
      shortName: "IND",
      logoUrl: "https://example.com/india-logo.png",
      players: [
        { id: "player-001", name: "Rohit Sharma", teamId: "team-001" },
        { id: "player-002", name: "Virat Kohli", teamId: "team-001" },
        { id: "player-003", name: "KL Rahul", teamId: "team-001" },
        { id: "player-004", name: "Rishabh Pant", teamId: "team-001" },
        { id: "player-005", name: "Hardik Pandya", teamId: "team-001" },
        { id: "player-006", name: "Ravindra Jadeja", teamId: "team-001" },
        { id: "player-007", name: "R Ashwin", teamId: "team-001" },
        { id: "player-008", name: "Jasprit Bumrah", teamId: "team-001" },
        { id: "player-009", name: "Mohammed Shami", teamId: "team-001" },
        { id: "player-010", name: "Yuzvendra Chahal", teamId: "team-001" },
        { id: "player-011", name: "Mohammed Siraj", teamId: "team-001" },
      ],
    },
    team2: {
      id: "team-002",
      name: "Australia",
      shortName: "AUS",
      logoUrl: "https://example.com/australia-logo.png",
      players: [
        { id: "player-012", name: "David Warner", teamId: "team-002" },
        { id: "player-013", name: "Aaron Finch", teamId: "team-002" },
        { id: "player-014", name: "Steve Smith", teamId: "team-002" },
        { id: "player-015", name: "Glenn Maxwell", teamId: "team-002" },
        { id: "player-016", name: "Marcus Stoinis", teamId: "team-002" },
        { id: "player-017", name: "Alex Carey", teamId: "team-002" },
        { id: "player-018", name: "Pat Cummins", teamId: "team-002" },
        { id: "player-019", name: "Mitchell Starc", teamId: "team-002" },
        { id: "player-020", name: "Adam Zampa", teamId: "team-002" },
        { id: "player-021", name: "Josh Hazlewood", teamId: "team-002" },
        { id: "player-022", name: "Nathan Lyon", teamId: "team-002" },
      ],
    },
  },
  tossWinner: "team-001",
  tossDecision: "BAT",
  currentInningsNumber: 1,
  maxOvers: 20,
  innings: [
    {
      id: "innings-001",
      teamId: "team-001",
      teamName: "India",
      battingOrder: ["player-001", "player-002", "player-003"],
      currentBatsmen: ["player-001", "player-002"],
      batsmen: {
        "player-001": {
          playerId: "player-001",
          runs: 24,
          balls: 18,
          fours: 3,
          sixes: 1,
          strikeRate: 133.33,
          isBatting: true,
          isOut: false,
        },
        "player-002": {
          playerId: "player-002",
          runs: 35,
          balls: 25,
          fours: 4,
          sixes: 2,
          strikeRate: 140.0,
          isBatting: true,
          isOut: false,
        },
      },
      bowlers: {
        "player-018": {
          playerId: "player-018",
          overs: 3,
          maidens: 0,
          runs: 22,
          wickets: 0,
          economy: 7.33,
        },
        "player-019": {
          playerId: "player-019",
          overs: 2.4,
          maidens: 0,
          runs: 32,
          wickets: 0,
          economy: 12.0,
        },
      },
      currentBowler: "player-019",
      totalRuns: 59,
      totalWickets: 0,
      totalOvers: 5,
      currentOverBalls: 4,
      extras: 0,
      overs: [],
      currentOver: [
        {
          id: "ball-001",
          ballNumber: 5.1,
          runs: 1,
          extraType: ExtraType.NONE,
          extraRuns: 0,
          wicketType: WicketType.NONE,
          striker: "player-001",
          nonStriker: "player-002",
          bowler: "player-019",
          timestamp: 1716978754000,
        },
        {
          id: "ball-002",
          ballNumber: 5.2,
          runs: 0,
          extraType: ExtraType.NONE,
          extraRuns: 0,
          wicketType: WicketType.NONE,
          striker: "player-002",
          nonStriker: "player-001",
          bowler: "player-019",
          timestamp: 1716978784000,
        },
        {
          id: "ball-003",
          ballNumber: 5.3,
          runs: 4,
          extraType: ExtraType.NONE,
          extraRuns: 0,
          wicketType: WicketType.NONE,
          striker: "player-002",
          nonStriker: "player-001",
          bowler: "player-019",
          timestamp: 1716978814000,
        },
        {
          id: "ball-004",
          ballNumber: 5.4,
          runs: 2,
          extraType: ExtraType.NONE,
          extraRuns: 0,
          wicketType: WicketType.NONE,
          striker: "player-002",
          nonStriker: "player-001",
          bowler: "player-019",
          timestamp: 1716978844000,
        },
      ],
      currentRunRate: 11.8,
      requiredRunRate: 0,
      maxOvers: 20,
    },
  ],
  matchHistory: [
    // Include all balls from the current over
    {
      id: "ball-001",
      ballNumber: 5.1,
      runs: 1,
      extraType: ExtraType.NONE,
      extraRuns: 0,
      wicketType: WicketType.NONE,
      striker: "player-001",
      nonStriker: "player-002",
      bowler: "player-019",
      timestamp: 1716978754000,
    },
    {
      id: "ball-002",
      ballNumber: 5.2,
      runs: 0,
      extraType: ExtraType.NONE,
      extraRuns: 0,
      wicketType: WicketType.NONE,
      striker: "player-002",
      nonStriker: "player-001",
      bowler: "player-019",
      timestamp: 1716978784000,
    },
    {
      id: "ball-003",
      ballNumber: 5.3,
      runs: 4,
      extraType: ExtraType.NONE,
      extraRuns: 0,
      wicketType: WicketType.NONE,
      striker: "player-002",
      nonStriker: "player-001",
      bowler: "player-019",
      timestamp: 1716978814000,
    },
    {
      id: "ball-004",
      ballNumber: 5.4,
      runs: 2,
      extraType: ExtraType.NONE,
      extraRuns: 0,
      wicketType: WicketType.NONE,
      striker: "player-002",
      nonStriker: "player-001",
      bowler: "player-019",
      timestamp: 1716978844000,
    },
  ],
  events: [],
};
